### PR TITLE
Multiple keyWord files, deviation from default point deduction

### PR DESCRIPTION
**Pull request by srinath99**
Hi Keegan,

I've made a few changes to the program and am submitting this so that you can adopt the ones you want. A lot of the changes involve personalizing the message to my format and other customization, specifically changing the ANSI color sequences to the Windows 10 console values and adding stringstream (because my compiler didn't understand std::to_string(), so you probably don't want to merge than particular change).

The changes I think that would be applicable to you are the following:

-I modified the code so that a different keyWord list would be maintained for each class. I feel that this would be more organized and you can maintain different point values for those deductions that overlap (for example 278 is out of 45 points, so a 10% deduction would be -4. 254 is out of 70 points, so 10% would be -7)

-I also added another prompt that asks if you would like to change the default point deduction. I found this to be especially useful when going through 254, since I would do -1 if the deduction was in one of the files and -2 if it was in both files. This way, I can just maintain a single keyWord, assign a default deduction, and enter my new deduction for just that student. If the default deduction is the one I want to ultimately go with, I just press enter and it will stick with the default.

Feel free to accept/reject/modify any/all of these changes that I have! If you have any questions, don't hesitate to shoot me an email. Thanks again for sharing this tool with me.

-Srinath

### CODE REVIEW

**Review by keegandonley — COMMENTED** [review]
I like it! Thanks for contributing. I work all week so I probably won't get to this until the weekend

**Comment by keegandonley** [comment]
@srinath99 Hey, took a closer look at the changes. Since everything is rolled into one commit, I can't really separate out the generic improvements over your personal changes. If you have time and want to, can you open another PR with just the updated features below?

> -I modified the code so that a different keyWord list would be maintained for each class. I feel that this would be more organized and you can maintain different point values for those deductions that overlap (for example 278 is out of 45 points, so a 10% deduction would be -4. 254 is out of 70 points, so 10% would be -7)

> -I also added another prompt that asks if you would like to change the default point deduction. I found this to be especially useful when going through 254, since I would do -1 if the deduction was in one of the files and -2 if it was in both files. This way, I can just maintain a single keyWord, assign a default deduction, and enter my new deduction for just that student. If the default deduction is the one I want to ultimately go with, I just press enter and it will stick with the default.

This way, you can get credit for the changes instead of me going through and manually adding the lines!

**Comment by srinath99** [comment]
Hi Keegan,

Sounds good. Looks like I have to restructure the git repo a bit to do
that, so I'll get to it this weekend.

Srinath

**Comment by keegandonley** [comment]
Closing this for now. If you decide to implement the changes discussed above, we can start a new PR

thanks!

**Pull request closed without merging**
